volumes:
  pg_data:
  static:
  media:
  frontend_build:

services:
  db:
    image: postgres:15
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  
  backend:
    image: bobah2060/foodgram-backend
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/backend_media
    depends_on:
      - db


  frontend:
    image: bobah2060/foodgram-frontend
    command: cp -r /app/build/. /frontend_build/
    volumes:
      - static:/frontend_build

  gateway:
    image: bobah2060/foodgram-gateway
    env_file: .env
    ports:
      - "9000:80"
    depends_on:
      - backend
      - frontend
    volumes:
      - static:/staticfiles
      - media:/mediafiles
